"""

Revision ID: 0b190e164eae
Revises: 8490aa3e87d0
Create Date: 2017-03-03 20:55:21.881572

"""

# revision identifiers, used by Alembic.
revision = '0b190e164eae'
down_revision = '8490aa3e87d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eb_id', sa.String(length=90), nullable=True),
    sa.Column('eb_parent_id', sa.String(length=90), nullable=True),
    sa.Column('eb_name', sa.String(length=255), nullable=True),
    sa.Column('eb_name_short', sa.String(length=90), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_eb_id'), 'categories', ['eb_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_eb_id'), table_name='categories')
    op.drop_table('categories')
    ### end Alembic commands ###
