"""adds category_id and subcategory_id

Revision ID: 8490aa3e87d0
Revises: 0ee344e2a40f
Create Date: 2017-03-03 20:33:25.880386

"""

# revision identifiers, used by Alembic.
revision = '8490aa3e87d0'
down_revision = '0ee344e2a40f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('eb_category_id', sa.String(), nullable=True))
    op.add_column('events', sa.Column('eb_subcategory_id', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'eb_subcategory_id')
    op.drop_column('events', 'eb_category_id')
    ### end Alembic commands ###
