"""Add raw_eb_data to the events table

Revision ID: aecd50b9eaa4
Revises: 0b190e164eae
Create Date: 2018-03-10 17:52:31.071366

"""

# revision identifiers, used by Alembic.
revision = 'aecd50b9eaa4'
down_revision = '0b190e164eae'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('raw_eb_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'raw_eb_data')
    ### end Alembic commands ###
